# index
IndexAssembly: "hisat2"    # "hisat2" with genome or "kallisto" with transcriptome or  " " if you have index already
indexname: "genomehuman38" # Name the index or Type the name of index in "Assembly"

# Direct the analysis
map: "Genome"       # "Genome" or  "Transcriptome" 
end: "paired"       # "single" or "paired"
QC_fq: yes          # if you'd like to get only QC report regarding fq files
QC_align: yes       # if you'd like to get only QC report regarding bams files
ext:                # extension of fastq file
  f: ".fastq.gz"    # any extanstion of fastq file (paired & single)
  f1: "_R1_001.fastq.gz"     # any extanstion of fastq file (paired)
  f2: "_R2_001.fastq.gz"     # any extanstion of fastq file (paired)
  strandness: "RF"  # paired "FR" or "RF"  / single "F" or "R"

# Threads
th:
  max: 48
  normal: 16

# Assembly and Annotation files
Assembly: "Assembly/genome.fa" #genome/transcriptome fasta file
gtf: "Assembly/genome.gtf"     #genome/transcriptome gtf file
gtfqc: "Assembly/genome.gtf"  #genome gtf file for rnaseqc
