idir: "input"              #input diractery
ext :                       #extension of fastq file
  f: ".fastq.gz"
  f1: "_R1_001.fastq.gz"
  f2: "_R2_001.fastq.gz"
th:    #threads
  max: 48
  normal: 16
gen: "genome/genome"        #gene index for hisat2
gene_fa: "genome/genome.fa"
gft: "genome/genome.gtf" #gene gtf file

