#index
IndexAssembly: "hisat2"                 # "hisat2" or "kallisto" or  directary of index in folder called "Assembly"
indexname: "genomehuman38"              # Name the index or Type the name of index you have in "Assembly" folder

#Direct the analysis
map: "map_to_ganome"       # "map_to_ganome" or  "map_to_transcriptome"
end: "paired"              # "single" or "paired"
ext:                       #extension of fastq file
  f: ".fastq.gz"           # any extanstion of fastq file
  f1: "_R1_001"   # any extanstion of fastq file (forward)
  f2: "_R2_001"   # any extanstion of fastq file (reverse)
  strandness: "RF"         # paired "FR" or "RF"  / single "F" or "R"

#Threads
th:
  max: 48
  normal: 16

# Assembly and Annotation files
Assembly: "Assembly/genome.fa" #gene/transcriptome fasta file
gtf: "Assembly/genome.gtf"    #gene/transcriptome gtf file
