# index
IndexAssembly: ""    # "hisat2" with genome or "kallisto" with transcriptome or  " " if you have index already
indexname: "" # Name the index or Type the name of index in "Assembly"

# Direct the analysis
map: ""       # "Genome" or  "Transcriptome" 
end: ""       # "single" or "paired"

ext:                # extension of fastq file
  f: ""    # any extanstion of fastq file (paired & single)   e.g. ".fastq.gz"
  f1: ""     # any extanstion of fastq file (paired)          e.g. "_R1.fastq.gz"
  f2: ""     # any extanstion of fastq file (paired)          e.g. "_R2.fastq.gz"
  strandness: ""  # paired "FR" or "RF"  / single "F" or "R"

# Threads
th:
  max: 48
  normal: 16

# Assembly and Annotation files
Assembly: "Assembly/genome.fa" #genome/transcriptome fasta file
gtf: "Assembly/genome.gtf"     #genome/transcriptome gtf file
gtfqc: "Assembly/genome.gtf"  #genome gtf file for rnaseqc
