idir: "input"              #input diractery
odir :                     #output diractery
  qc: "qc"
  s1: "stap1"
  s2: "stap2"
  s3: "stap3"
  s4: "stap4"
  s5: "stap5"
eff :                       #extension of fastq file
  f: ".fastq.gz"
  f1: "_R1_001.fastq.gz"
  f2: "_R2_001.fastq.gz"
threads:
  max: 48
  normal: 10