# index
IndexAssembly: ""    # "hisat2" or "kallisto" or  " "
indexname: "Homo_sapiens.GRCh38.dna.chromosome.1.1.10M" # Name the index or Type the name of index in "Assembly"

# Direct the analysis
map: "Genome"       # "Genome" or  "Transcriptome" or "Noval_splice_variants"
end: "paired"       # "single" or "paired"
ext:                # extension of fastq file
  f: ".fastq.gz"    # any extanstion of fastq file (paired & single)
  f1: "_R1.fastq.gz"     # any extanstion of fastq file (paired)
  f2: "_R2.fastq.gz"     # any extanstion of fastq file (paired)
  strandness: "RF"  # paired "FR" or "RF"  / single "F" or "R"

# Threads
th:
  max: 48
  normal: 16

# Assembly and Annotation files
Assembly: "Assembly/Homo_sapiens.GRCh38.dna.chromosome.1.1.10M.fa" #genome/transcriptome fasta file
gtf: "Assembly/Homo_sapiens.GRCh38.93.1.1.10M.gtf"     #genome/transcriptome gtf file
gtfqc: "Assembly/Homo_sapiens.GRCh38.93.1.1.10M_TXT.gtf"  #genome gtf file for rnaseqc
